package gui;
/*
 * @author HongAnh
 * @created 15 / 02 / 2024 - 7:42 PM
 * @project IntelliJ IDEA
 * @social Github: https://github.com/lehonganh0201
 */

import domain.Event;
import domain.User;
import service.EventService;
import service.UserService;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

public class AdminEventManagerFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminEventManagerFrame
     */
    public AdminEventManagerFrame() {
        eventService = new EventService();
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        txtNameInput = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        preBtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null}
                },
                new String [] {
                        "ID", "Name", "Location", "PriceTicket", ""
                }
        ));
        jScrollPane1.setViewportView(jTable1);

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        preBtn.setText("<");
        preBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preBtnActionPerformed(evt);
            }
        });

        nextBtn.setText(">");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchBtn)
                                .addContainerGap(94, Short.MAX_VALUE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(backBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(preBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nextBtn)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(searchBtn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(backBtn)
                                        .addComponent(preBtn)
                                        .addComponent(nextBtn)))
        );

        pack();

        jTable1.getColumnModel().getColumn(4).setCellRenderer(new ButtonRenderer());
        jTable1.getColumnModel().getColumn(4).setCellEditor(new AdminEditor(new JCheckBox()));
        jTable1.setRowHeight(50);
        tableModel = (DefaultTableModel) jTable1.getModel();
        updateEventData(eventService.showListEvent());
    }// </editor-fold>

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        List<Event> list = eventService.getEventByName(txtNameInput.getText());
        updateEventData(list);
    }

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        AdminHome adminHome = new AdminHome(LoginFrame.user);
        adminHome.setVisible(true);
        dispose();
    }

    private void preBtnActionPerformed(java.awt.event.ActionEvent evt) {
        if(currentPage > 1){
            currentPage--;
            updateEventData(eventService.showListEvent());
        }
    }

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {
        int maxPage = (int) Math.ceil((double) eventService.showListEvent().size() / eventsPerPage);
        if (currentPage < maxPage) {
            currentPage++;
            updateEventData(eventService.showListEvent());
        }
    }

    private void updateEventData(List<Event> events) {
        if(events != null){
            tableModel.setRowCount(0);

            int startIndex = (currentPage - 1) * eventsPerPage;
            int endIndex = Math.min(startIndex + eventsPerPage, events.size());

            for (int i = startIndex; i < endIndex; i++) {
                domain.Event event = events.get(i);

                Object[] rowData = {
                        event.getEventId(),
                        event.getName(),
                        event.getPlace(),
                        event.getPrice(),
                        "REMOVE"
                };
                tableModel.addRow(rowData);
            }

            jTable1.getColumnModel().getColumn(4).setCellRenderer(new ButtonRenderer());
            jTable1.getColumnModel().getColumn(4).setCellEditor(new AdminEditor(new JCheckBox()));
        }
    }

    // Variables declaration - do not modify
    private javax.swing.JButton backBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton nextBtn;
    private javax.swing.JButton preBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField txtNameInput;
    private DefaultTableModel tableModel;
    private int currentPage = 1;
    private int eventsPerPage = 5;
    private final EventService eventService;
    // End of variables declaration
}
