/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import domain.Event;
import domain.User;
import service.EventService;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.util.List;

/**
 *
 * @author PC
 */
public class RegistedUserFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegistedUserFrame
     */
    public RegistedUserFrame(Event event) {
        eventService = new EventService();
        initComponents(event);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents(Event event) {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        createGroupBtn = new javax.swing.JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        createGroupBtn.setText("Create Group");
        createGroupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createGroupBtnActionPerformed(evt,event);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null},
                        {null, null, null},
                        {null, null, null},
                        {null, null, null}
                },
                new String [] {
                        "STT", "Name", "Remove"
                }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(createGroupBtn)
                                .addContainerGap(154, Short.MAX_VALUE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(createGroupBtn)
                                .addContainerGap())
        );

        pack();

        tableModel = (DefaultTableModel) jTable1.getModel();
        updateUserData(eventService.getUserByEvent(event),event);
    }// </editor-fold>

    private void createGroupBtnActionPerformed(java.awt.event.ActionEvent evt,Event event) {
        // TODO add your handling code here:

        CreateGroupFrame frame = new CreateGroupFrame(event);
        frame.setVisible(true);
    }

    private void updateUserData(List<domain.User> users,Event event){
        tableModel.setRowCount(0);
        for(User user:users){
            Object[] rowData = {
                    user.getUserId(),
                    user.getFullName(),
                    "-"
            };
            tableModel.addRow(rowData);
        }

        jTable1.getColumnModel().getColumn(2).setCellRenderer(new ButtonRenderer());
        jTable1.getColumnModel().getColumn(2).setCellEditor(new ButtonCompiler(new JCheckBox(),event));
    }

    // Variables declaration - do not modify
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private DefaultTableModel tableModel;
    private final EventService eventService;
    private javax.swing.JButton createGroupBtn;
    // End of variables declaration
}
