/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import domain.Event;
import domain.EventPost;
import domain.User;
import service.EventService;
import service.UserService;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

/*
 * @author HongAnh
 * @created 07 / 02 / 2024 - 5:03 PM
 * @project IntelliJ IDEA
 * @social Github: https://github.com/lehonganh0201
 */
public class ViewEventDetailsFrame extends javax.swing.JFrame {

    /**
     * Creates new form ViewEventDetailsFrame
     */
    public ViewEventDetailsFrame(Event event) {
        userService = new UserService();
        eventService = new EventService();
        initComponents(event);
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents(Event event) {

        eventName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        JLabel2 = new javax.swing.JLabel();
        Jlabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LeaveBtn = new javax.swing.JButton();
        JoinBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        StartDateLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        EndDateLabel = new javax.swing.JLabel();
        PlaceLabel = new javax.swing.JLabel();
        PriceLabel = new javax.swing.JLabel();
        OrganizersLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contentText = new javax.swing.JTextArea();
        usernameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);


        StartDateLabel.setText(String.valueOf(event.getStartDateTime()));
        EndDateLabel.setText(String.valueOf(event.getEndDateTime()));
        PriceLabel.setText(String.valueOf(event.getPrice()));
        PlaceLabel.setText(String.valueOf(event.getPlace()));
        User user = userService.getUserById(LoginFrame.user.getUserId());
        OrganizersLabel.setText(user.getFullName());

        eventName.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        eventName.setText(event.getName());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Start Date:");

        JLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabel2.setText("End Date:");

        Jlabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Jlabel3.setText("Place:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Price");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Organizers:");

        LeaveBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LeaveBtn.setText("Leave");
        LeaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeaveBtnActionPerformed(evt,event);
            }
        });

        JoinBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JoinBtn.setText("Join");
        JoinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JoinBtnActionPerformed(evt,event);
            }
        });

        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        StartDateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        EndDateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        PlaceLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        PriceLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        OrganizersLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        List<EventPost> eventPosts = userService.viewEventPosts(event);
        jPanel1 = new javax.swing.JPanel();
        jPanel1.setLayout(new GridLayout(eventPosts.size(), 1)); // Sử dụng GridLayout để chia các post thành các hàng

        for(EventPost post : eventPosts) {
            JPanel postPanel = new JPanel();
            postPanel.setLayout(new BorderLayout());

            User postUser = userService.getUserById(post.getUser().getUserId());
            JLabel postUsernameLabel = new javax.swing.JLabel();
            postUsernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14));
            postUsernameLabel.setText(postUser.getFullName());

            JTextArea postContentText = new javax.swing.JTextArea();
            postContentText.setColumns(20);
            postContentText.setRows(5);
            postContentText.setText(post.getText());
            postContentText.setEditable(false);
            JScrollPane postScrollPane = new JScrollPane(postContentText);

            postPanel.add(postUsernameLabel, BorderLayout.NORTH);
            postPanel.add(postScrollPane, BorderLayout.CENTER);

            jPanel1.add(postPanel);
        }


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(Jlabel3)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(PlaceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(PriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(StartDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(JLabel2)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(0, 79, Short.MAX_VALUE))
                                                                        .addComponent(EndDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel4)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(OrganizersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(101, 101, 101)
                                                                .addComponent(eventName))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(BackBtn)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(LeaveBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JoinBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(eventName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(StartDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(JLabel2)
                                                .addComponent(jLabel6)
                                                .addComponent(EndDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Jlabel3)
                                        .addComponent(jLabel2)
                                        .addComponent(PlaceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel3))
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(PriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(OrganizersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LeaveBtn)
                                        .addComponent(JoinBtn))
                                .addGap(18, 18, 18)
                                .addComponent(BackBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();
    }

    private void LeaveBtnActionPerformed(java.awt.event.ActionEvent evt,Event event) {
        userService.cancelEventRegistration(LoginFrame.user,event);
    }

    private void JoinBtnActionPerformed(java.awt.event.ActionEvent evt,Event event) {
        ListGroupFrame listGroupFrame = new ListGroupFrame(event);
        listGroupFrame.setVisible(true);
    }

    private void openRegisteredEvent(){
        RegisteredEventsFrame registeredEventsFrame = new RegisteredEventsFrame(LoginFrame.user);
        registeredEventsFrame.setVisible(true);
        dispose();
    }

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {
        MainScreen mainScreen = new MainScreen();
        mainScreen.setVisible(true);
        dispose();
    }

    // Variables declaration - do not modify
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel EndDateLabel;
    private javax.swing.JLabel JLabel2;
    private javax.swing.JLabel Jlabel3;
    private javax.swing.JButton JoinBtn;
    private javax.swing.JButton LeaveBtn;
    private javax.swing.JLabel OrganizersLabel;
    private javax.swing.JLabel PlaceLabel;
    private javax.swing.JLabel PriceLabel;
    private javax.swing.JLabel StartDateLabel;
    private javax.swing.JTextArea contentText;
    private javax.swing.JLabel eventName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel usernameLabel;

    private final UserService userService;
    private final EventService eventService;
    // End of variables declaration
}
